/**
 * `X-Line-Retry-Key` for a push (05 §1 fact 8, §5.5). LINE takes a UUID "generated by any method"
 * in lowercase hexadecimal with dashes, remembers it for 24 hours, and answers a request sent again
 * under it with 409 and the first request's message ids, provided the body is exactly the same.
 *
 * The key is a version-5 UUID (RFC 9562 §5.5) of the outbound row's idempotency key and the
 * request's place in the message. So every retry of a row, whenever and wherever it runs, sends
 * each request under the key it had the first time, and no two requests share one.
 */

/**
 * Generated once for Vela. Changing it would give every message retried across the change new
 * keys, and LINE would send it again.
 */
export const LINE_RETRY_KEY_NAMESPACE = "4bb5ce48-b344-4a40-ba0d-47ccf5a221c2";

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

const encoder = new TextEncoder();

export function lineRetryKey(idempotencyKey: string, requestIndex: number): Promise<string> {
  return uuidV5(LINE_RETRY_KEY_NAMESPACE, `${idempotencyKey}#${requestIndex}`);
}

/** RFC 9562 §5.5: SHA-1 of the namespace's 16 bytes and the name's UTF-8, cut to 128 bits. */
export async function uuidV5(namespace: string, name: string): Promise<string> {
  if (!UUID.test(namespace)) throw new TypeError("namespace is not a lowercase UUID");
  const namespaceBytes = Uint8Array.from(namespace.replaceAll("-", "").match(/../g) ?? [], (pair) =>
    Number.parseInt(pair, 16),
  );
  const nameBytes = encoder.encode(name);
  const input = new Uint8Array(namespaceBytes.length + nameBytes.length);
  input.set(namespaceBytes);
  input.set(nameBytes, namespaceBytes.length);
  const digest = new Uint8Array(await crypto.subtle.digest("SHA-1", input)).subarray(0, 16);
  const hex = Array.from(digest, (byte, index) => {
    // The version (5) takes the high nibble of byte 6, the variant (binary 10) the top of byte 8.
    if (index === 6) return (byte & 0x0f) | 0x50;
    if (index === 8) return (byte & 0x3f) | 0x80;
    return byte;
  })
    .map((byte) => byte.toString(16).padStart(2, "0"))
    .join("");
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}
